#!/bin/sh
### BEGIN INIT INFO
# Provides:          __NAME__
# Required-Start:    $network $syslog postgresql nginx
# Required-Stop:     $network $syslog postgresql nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start __NAME__ at boot time
# Description:       Enable __NAME__ service.
### END INIT INFO

dir="__PDIR__"
cmd="__PDIR__/.local/bin/gunicorn project.wsgi:application"
user="__USER__"
name="__NAME__"

################################################################################

export $(grep -v '^#' "__PDIR__/.env" | xargs)
pid_file="/var/run/$name.pid"

is_running() {
    [ -f "$pid_file" ] && ps $(cat "$pid_file") > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"

        touch "$pid_file" "$stdout_log" "$stderr_log"
        if [ -z "$user" ]; then
            $cmd &
        else
            chown "$user" "$pid_file" "$stdout_log" "$stderr_log"
            su -m "$user" -c "$cmd" &
        fi
        pid="$!"
        if [ "$pid" = "0" ]; then
            echo "Unable to start __NAME__"
            exit 1
        else
            echo "$pid" > "$pid_file"
        fi
    fi
    ;;

    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill $(cat "$pid_file")
        for i in {1..10}; do
            if ! is_running; then break; fi
            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then rm "$pid_file"; fi
        fi
    else
        echo "Not running"
    fi
    ;;

    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;

    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;

    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
